services:
  pg_database:
    container_name: "pg_database"
    image: postgres:13-alpine
    ports:
      - "5439:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: "postgres -c max_connections=150 -c shared_buffers=521mb"
    env_file:
      - ".env"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  api:
    stop_signal: SIGINT
    build:
      context: ./backend
      dockerfile: backend/api.Dockerfile
    working_dir: "/usr/src/app/api"
    volumes:
      - ./backend/:/usr/src/app/api
    command:
      [
        "uvicorn",
        "infrastructure.api.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
